import type { Metadata } from 'next';

import './globals.css';
import { cn } from '@/lib/utils';
import { fontPoppins, fontSans } from '@/lib/fonts';
import Layout from '@/components/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'font-sans antialiased',
          fontSans.variable,
          fontPoppins.variable
        )}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
